name = "Stock Trader"
id = "stock-trader"
version = "0.0.0"
type = "mod"
requires = "none"

[Spawner]
limit = 1 # Max amount of child processes to spawn

[Puppet]
headless = false
initLink = 'https://www.tradingview.com/chart/AjbMCPap/'
