name = "Stock Trader"
id = "stock-trader"
version = "0.0.0"
type = "mod"
requires = "none"
disabled = false

[Puppet]
headless = false
initLink = 'https://www.tradingview.com/'
chartLink = 'https://www.tradingview.com/chart/AjbMCPap/'

[Puppet.View]
width = 1600
height = 900
