name = "Stock Trader"
id = "stock-trader"
version = "0.0.0"
type = "mod"
requires = "none"

[Spawner]
limit = 8 # Max amount of child processes to spawn

[Puppet]
headless = true
initLink = 'https://www.tradingview.com/'

[Puppet.View]
width = 1600
height = 900
